service: price-service 

functions:
  cmcprice:
    name: cmcprice
    handler: handler.updateprice
    events:
      - schedule: rate(1 minute)

resources:
  Resources:
    DynamoDBTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "CryptoPrices"
        BillingMode: "PAY_PER_REQUEST"
        AttributeDefinitions:
          -
            AttributeName: "currency"
            AttributeType: "S"
        KeySchema:
          -
            AttributeName: "currency"
            KeyType: "HASH"