service: ethttt-if-be

plugins:
  - serverless-dynamodb-local
  - serverless-dotenv-plugin
  - serverless-offline

custom:
  dynamodb:
    stages:
      - dev
    start:
      port: 8000
      inMemory: true
      migrate: true

provider:
  name: aws
  runtime: nodejs8.10
  # region: us-east-1

  iamRoleStatements:
    - Effect: "Allow"
      Action:
        - "dynamodb:PutItem"
        - "dynamodb:Query"
        - "dynamodb:Scan"
        - "dynamodb:GetItem"
        - "dynamodb:PutItem"
        - "dynamodb:UpdateItem"
        - "dynamodb:DeleteItem"
      Resource: !GetAtt DynamoDBTable.Arn

# you can define service wide environment variables here
# environment:
#   SLS_DEBUG: '*'

functions:
  hello:
    handler: handler.hello
    events:
      - http:
          path: '/'
          method: get
          cors: true
  # getEthPrice:
  #   handler: handler.getEthPrice
  #   events: 
  #     - schedule: rate(1 minute)
  # getUser:
  #   handler: users/get/index.get
  #   events:
  #     - http:
  #       path: users/{ethAddress}
  #       method: get
  #       cors: true
  createUser:
    handler: users/create/index.create
    events:
      - http:
          path: /users
          method: post
          cors: true

resources:
  Resources:
    usersTable:
      Type: AWS::DynamoDB::Table
      Properties:
        TableName: "usersTable"
        AttributeDefinitions:
          - AttributeName: "address"
            AttributeType: S
        KeySchema:
          - AttributeName: "address"
            KeyType: HASH
        ProvisionedThroughput:
          ReadCapacityUnits: 1
          WriteCapacityUnits: 1